# Docker image for Continuous integration 
name: Docker Build and Deploy

on:
  push:
    branches: [main]

jobs: 
  build:
    runs-on:  ubuntu-latest

    steps
    - uses: actions/checkout@v2
      name: checkout code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: build and push docker image for feed
      with:
        image: savytech/udagram-api-feed
        tags: v5,latest
        registry: docker.io
        directory: udagram-api-feed
        dockerfile: udagram-api-feed/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: build and push docker image for user
      with:
        image: savytech/udagram-api-user
        tags: v6,latest
        registry: docker.io
        directory: udagram-api-user
        dockerfile: udagram-api-user/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: build and push docker image for frontend
      with:
        image: savytech/udagram-frontend
        tags: v7,latest
        registry: docker.io
        directory: udagram-frontend
        dockerfile: udagram-frontend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 

        - uses: mr-smithers-excellent/docker-build-push@v5
      name: build and push docker image for reverseproxy
      with:
        image: savytech/udagram-reverseproxy
        tags: v5,latest
        registry: docker.io
        directory: udagram-reverseproxy
        dockerfile: udagram-reverseproxy/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
